spring.application.name=api
spring.datasource.url=jdbc:h2:mem:api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.security.user.name=${APP_SECURITY_USER}
spring.security.user.password=${APP_SECURITY_PASSWORD}
gemini.api.key=${GEMINI_API_KEY:}
